from homeassistant.components.sensor import (
    SensorDeviceClass
)

FriendlyMap = {
  # System info
  'connectors':                       "Number of available connectors",
  'hwrevision':                       "Hardware revision",
  'model':                            "Model identifier",
  'serial':                           "Serial number",
  'swrevision':                       "Software revision",
  # Connector info
  'active_session_duration':          "Active session duration",
  'active_session_imported_energy':   "Active session imported energy",
  'ev_max_phase_current':             "EV max phase current",
  'ev_max_power':                     "EV max power",
  'ev_required_energy':               "EV required energy",
  'l1_active_power':                  "Active Power (L1)",
  'l1_current':                       "Active Current (L1)",
  'l1_ln_voltage':                    "L-N voltage (L1)",
  'l1_phase':                         "Phase (L1)",
  'l2_active_power':                  "Active Power (L2)",
  'l2_current':                       "Active Current (L2)",
  'l2_ln_voltage':                    "L-N voltage (L2)",
  'l2_phase':                         "Phase (L2)",
  'l3_active_power':                  "Active Power (L3)",
  'l3_current':                       "Active Current (L3)",
  'l3_ln_voltage':                    "L-N voltage (L3)",
  'l3_phase':                         "Phase (L3)",
  'max_current':                      "Max current",
  'net_frequency':                    "Net frequency",
  'num_phases':                       "Number of available phases",
  'power_factor':                     "Power factor",
  'session_departure_time':           "End time of last session (Unix seconds)",
  'session_id':                       "Session ID",
  'state':                            "Current charger state",
  'state_numeric':                    "Current charger state id (numeric code)",
  'target_current':                   "Target current for current charge",
  'total_active_power':               "Total active charging power",
  'type':                             "Type of cable to vehicle",
  'type_numeric':                     "Type of cable to vehicle id (numeric code)",
  'vehicle_connected_phases':         "Number of phases connected to vehicle",
  'vehicle_connected_phases_code':    "Number of phases connected to vehicle id (numeric code)",
  'vehicle_connected_phases_numeric': "Actual number of phases connected to veehicle"
}

DeviceMap = {
  # System info
  'connectors':                       None,
  'hwrevision':                       None,
  'model':                            None,
  'serial':                           None,
  'swrevision':                       None,
  # Connector info
  'active_session_duration':          SensorDeviceClass.DURATION,
  'active_session_imported_energy':   SensorDeviceClass.ENERGY,
  'ev_max_phase_current':             SensorDeviceClass.CURRENT,
  'ev_max_power':                     SensorDeviceClass.POWER,
  'ev_required_energy':               SensorDeviceClass.POWER,
  'l1_active_power':                  SensorDeviceClass.POWER,
  'l1_current':                       SensorDeviceClass.CURRENT,
  'l1_ln_voltage':                    SensorDeviceClass.VOLTAGE,
  'l1_phase':                         None,
  'l2_active_power':                  SensorDeviceClass.POWER,
  'l2_current':                       SensorDeviceClass.CURRENT,
  'l2_ln_voltage':                    SensorDeviceClass.VOLTAGE,
  'l2_phase':                         None,
  'l3_active_power':                  SensorDeviceClass.POWER,
  'l3_current':                       SensorDeviceClass.CURRENT,
  'l3_ln_voltage':                    SensorDeviceClass.VOLTAGE,
  'l3_phase':                         None,
  'max_current':                      SensorDeviceClass.CURRENT,
  'net_frequency':                    SensorDeviceClass.FREQUENCY,
  'num_phases':                       None,
  'power_factor':                     SensorDeviceClass.POWER_FACTOR,
  'session_departure_time':           SensorDeviceClass.TIMESTAMP,
  'session_id':                       None,
  'state':                            None,
  'state_numeric':                    None,
  'target_current':                   SensorDeviceClass.CURRENT,
  'total_active_power':               SensorDeviceClass.POWER,
  'type':                             None,
  'type_numeric':                     None,
  'vehicle_connected_phases':         None,
  'vehicle_connected_phases_code':    None,
  'vehicle_connected_phases_numeric': None
}

UnitMap = {
  # System info
  'connectors':                       "",
  'hwrevision':                       "",
  'model':                            "",
  'serial':                           "",
  'swrevision':                       "",
  # Connector info
  'active_session_duration':          "s",
  'active_session_imported_energy':   "kWh",
  'ev_max_phase_current':             "A",
  'ev_max_power':                     "kW",
  'ev_required_energy':               "kW",
  'l1_active_power':                  "W",
  'l1_current':                       "A",
  'l1_ln_voltage':                    "V",
  'l1_phase':                         "",
  'l2_active_power':                  "W",
  'l2_current':                       "A",
  'l2_ln_voltage':                    "V",
  'l2_phase':                         "",
  'l3_active_power':                  "W",
  'l3_current':                       "A",
  'l3_ln_voltage':                    "A",
  'l3_phase':                         "",
  'max_current':                      "A",
  'net_frequency':                    "Hz",
  'num_phases':                       "",
  'power_factor':                     "%",
  'session_departure_time':           "s",
  'session_id':                       "",
  'state':                            "",
  'state_numeric':                    "",
  'target_current':                   "A",
  'total_active_power':               "kW",
  'type':                             "",
  'type_numeric':                     "",
  'vehicle_connected_phases':         "",
  'vehicle_connected_phases_code':    "",
  'vehicle_connected_phases_numeric': ""
}
